### PR TITLE
fix(dupe-messages): only display supabase msg events

### LINKED ISSUE #85: Optimistic/Realtime dedup race condition in ConversationView.tsx (State bug)
The sender adds an optimistic message with a random UUID (ConversationView.tsx:336). The Realtime INSERT subscription dedup check (line 199) compares by DB id (`newMsg.id`), but the optimistic message still has the random UUID — so the check misses and the message is added a second time. When the API response arrives (line 367), it swaps the optimistic ID to the real DB id, producing two entries with the same React key.

### Steps to reproduce

1. Open `/messages` in browser A (user 1), DevTools Console open
2. Open `/messages` in a private/incognito window (user 2)
3. From user 2, **start a new conversation** with user 1 and send a message (as quickly as you can)

**Expected:**
- User 1 sees the new conversation appear; no console errors
- User 2 sees their sent message once; no console errors

**Actual:**
- User 1 console: `Cannot update a component (Router) while rendering a different component (ConversationList)`
- User 2 console: `Encountered two children with the same key` on `ConversationView.tsx:671`
- Image

### Intended fix

1.  Move `router.refresh()` outside the `setConversations` updater. Use a ref or return a sentinel value from the updater, then call `router.refresh()` after the state update completes.

2. When the current user sends a message, skip Realtime INSERT handling for their own messages while an optimistic version is pending. Track pending optimistic IDs in a ref and filter them out in the Realtime callback.

### PR DESCRIPTION
**Pull request by xdhmoore**
Instead of manually managing the local messages list and also displaying events once supabase has issued an event (presumably with a new id that doesn't match our local id), this changes it so that we just rely on supabase events. All of a user's new posts to the conversation window will come from supabase events.

I have not been able to reproduce and test this, but I believe @GeorgeDover has, if he can weigh in.

If more testing is needed, I can follow up next weekend when I have more time.

### CODE REVIEW

**Comment by GeorgeDover** [comment]
I was able to reproduce the error in dev via a breakpoint within handleSend, creating a latency between server response and client's "optimistic" handling of message. Though this is around the wrong way (in prod the client would be first followed by slow server response), the effect is the same - duplicated messages logged in the chat.

I tested this with @xdhmoore's fix above and the problem was resolved. I think it's good to move ahead!

**Review by GeorgeDover — APPROVED** [review]

File: components/messages/ConversationView.tsx [hunk 1]
```diff
@@ -321,20 +321,6 @@ export function ConversationView({
...
-      content: text,
-      message_type: messageType,
-      metadata,
-      edited_at: null,
-      created_at: new Date().toISOString(),
-      sender: buildSenderProfile(currentUser),
-    };
-    setMessages((prev) => [...prev, optimisticMsg]);
-
     // Use the API route so the server can fire email notifications to other participants
```
Comment (tonyrosario) [inline components/messages/ConversationView.tsx:324]: fixed confirmed as well.

Do we think that the git commit history is enough for a future contributor to avoid adding back an optimistic insert?  or do we add another comment above 324?

```
// Message display is handled by the Realtime subscription — no optimistic insert needed.
// If restoring optimistic updates, deduplicate against incoming Realtime events to avoid
// the duplicate bug fixed in PR-70.
// Use the API route so the server can fire email notifications to other participants
```

**Review by tonyrosario — APPROVED** [review]

File: components/messages/ConversationView.tsx (hunk 1 above)
Comment (xdhmoore) [reply components/messages/ConversationView.tsx:324]: I wouldn't rely on git history, but I think if people are going to call `setMessages()` in this file, they will likely look and see where it is being called in the same file.
